trigger:
- main
- feature/*

variables:
  buildConfiguration: 'Release'

jobs:
- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 8.0.x
      displayName: 'Use .NET 8.0 sdk'
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: 'build.sh'
        arguments: '-configuration $(buildConfiguration) -target CiNonWin'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 8.0.x
      displayName: 'Use .NET 8.0 sdk'
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: 'build.sh'
        arguments: '-configuration $(buildConfiguration) -target CiNonWin'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - checkout: self
      fetchDepth: "0"
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 8.0.x
      displayName: 'Use .NET 8.0 sdk'
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: '-configuration $(buildConfiguration) -target Ci'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'
    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: "cobertura"
        summaryFileLocation: "$(Build.SourcesDirectory)/artifacts/coverage/*.xml"
        failIfCoverageEmpty: true
      displayName: 'Publish Code Coverage'
    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        packagesToPush: '$(Build.SourcesDirectory)/artifacts/nuget/**/*.nupkg;$(Build.SourcesDirectory)/artifacts/nuget/**/*.snupkg;!$(Build.SourcesDirectory)/artifacts/nuget/**/*.symbols.nupkg'
        publishVstsFeed: 'Embedded/Embedded'
        allowPackageConflicts: true


